### ISSUE TITLE
Asset directory( assets/cfg)  does not exist

### ISSUE THREAD

**Issue by NoemiNahomy** [trufi-association/trufi#1]
The  asset directory( assets/cfg)  and file app_config.json  doest not exist.

**Comment by mdoelker** [comment]
Hi Noemi. That file is not required, but could be used to load "secrets" (nothing is really secret when it is shipped to a user's device) that should not be versioned. It is totally possible to set the config values directly in https://github.com/trufi-association/trufi/blob/master/lib/main.dart
